apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 4
  
  selector:
    matchLabels:
      app: conversao-temperatura
  
  template:
    metadata:
      labels:
        app: conversao-temperatura

    spec:
      containers: 
      - name: conversao-temperatura
        image: ricardovessaro/conversao-temperatura:desafio1
        ports: 
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: conversao-temperatura

spec: 
  selector: 
      app: conversao-temperatura

  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000

  type: NodePort
